# @(#) XSLT
# $ANDR: www/lib/articles/the_ark/Makefile,v 1.4 2006/08/13 20:48:50 andr Exp $

include ../../../docbook.mk

CHUNK= chunk.xsl
CSS= /index.css

all: the_ark.html

rm:
	rm -rfv *.html *.htm
